---
- hosts: localhost
  tasks:
  - name:               "Get VCN data for Mastadon example"
    oracle.oci.oci_network_vcn_facts:
      compartment_id:   "ocid1.compartment.oc1..aaaaaaaax4nkky4yov3bahtf3cg226ya2ngsaru7vxkv6pavdjwzz5udsojq"
    register:           vcn
  
  - name:               "Display Virtual Cloud Networks"
    ansible.builtin.debug:
      var:              vcn.vcns
    when:
      -                 vcn is defined
      -                 vcn.vcns is defined
  
  - name:               "Fetches details about one or multiple Subnet resources in Mastadon example"
    oracle.oci.oci_network_subnet_facts:
      compartment_id:   "{{ vcn.vcns[0].compartment_id }}"
      vcn_id:           "{{ vcn.vcns[0].id }}"
    register:           subnet
    when:
      -                 vcn is defined
      -                 vcn.vcns is defined
  
  - name:               "Display SubNets"
    ansible.builtin.debug:
      var:              subnet.subnets
    when:
      -                 subnet is defined
      -                 subnet.subnets is defined
...
