---
# ------------------------------------------------------------------------------
# Examine VCN/Subnets Characteristics
# ===================================
#
# Finds all VCNs and Subnets in the following two (2) compartments:
# 1. mastadon_compartment
# 2. Sandbox
# ------------------------------------------------------------------------------

- hosts: localhost
  vars:
    OCI_CLI_TENANCY:    "ocid1.tenancy.oc1..aaaaaaaa7ilqdzmkbqduujc3tt6zrl2n2ytcughcjoidozg4memj2k4cm7na"
  tasks:
  - name:               "Get Required Compartment Facts"
    oracle.oci.oci_identity_compartment_facts:
      parent_compartment_id:
                        "{{ OCI_CLI_TENANCY }}"
      name:             "{{ item }}"
    register:           required_compartment
    loop:
      -                 "mastadon_compartment"
      -                 "Sandbox"
  
  - name:               "Display Required Compartment Facts"
    ansible.builtin.debug:
      var:              required_compartment
    when:
      -                 required_compartment is defined
  
  - name:               "Save Compartment IDs for Required Compartments"
    ansible.builtin.set_fact:
      mastadon_comp_id: "{{ required_compartment.results[0].compartments[0].id }}"
      sandbox_comp_id:  "{{ required_compartment.results[1].compartments[0].id }}"

  - name:               "Get VCN data"
    oracle.oci.oci_network_vcn_facts:
      compartment_id:   "{{ item }}"
    register:           vcn
    loop:
      -                 "{{ mastadon_comp_id }}"
      -                 "{{ sandbox_comp_id }}"
  
  - name:               "Display VCN Data"
    ansible.builtin.debug:
      var:              vcn
    when:
      -                 vcn is defined
  
  - name:               "Save VCN IDs for Required Compartments"
    ansible.builtin.set_fact:
      req_vcn_ids:
        - comp_id:      "{{ mastadon_comp_id }}"
          vcn_id:       "{{ vcn.results[0].vcns[0].id }}"
        - comp_id:      "{{ sandbox_comp_id }}"
          vcn_id:       "{{ vcn.results[1].vcns[0].id }}"

  - name:               "Get Subnet data"
    oracle.oci.oci_network_subnet_facts:
      compartment_id:   "{{ item.comp_id }}"
      vcn_id:           "{{ item.vcn_id }}"
    register:           subnet
    loop:               "{{ req_vcn_ids }}"
  
  - name:               "Display Subnet Data"
    ansible.builtin.debug:
      var:              subnet
    when:
      -                 subnet is defined
...
